# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(831, 413)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sensR = QtWidgets.QDial(self.centralwidget)
        self.sensR.setGeometry(QtCore.QRect(40, 280, 71, 81))
        self.sensR.setMaximum(127)
        self.sensR.setObjectName("sensR")
        self.sensY = QtWidgets.QDial(self.centralwidget)
        self.sensY.setGeometry(QtCore.QRect(110, 280, 71, 81))
        self.sensY.setMaximum(127)
        self.sensY.setObjectName("sensY")
        self.sensG = QtWidgets.QDial(self.centralwidget)
        self.sensG.setGeometry(QtCore.QRect(180, 280, 71, 81))
        self.sensG.setMaximum(127)
        self.sensG.setObjectName("sensG")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
